/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThePiniaStore: typeof import('./src/components/ThePiniaStore.vue')['default']
    TheTestMock: typeof import('./src/components/TheTestMock.vue')['default']
    TheTestPiniaStore: typeof import('./src/components/TheTestPiniaStore.vue')['default']
    TheTestPiniaStore2: typeof import('./src/components/TheTestPiniaStore2.vue')['default']
    TheTestProps: typeof import('./src/components/TheTestProps.vue')['default']
    TheTestScss: typeof import('./src/components/TheTestScss.vue')['default']
    TheTestTailwind: typeof import('./src/components/TheTestTailwind.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
